services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: unless-stopped
    ports:
      - "${BOT_API_PORT:-8090}:${BOT_API_PORT:-8090}"
    environment:
      APP_ENV: ${APP_ENV}
      BOT_API_PORT: ${BOT_API_PORT:-8090}
      DEV_DISCORD_BOT_TOKEN: ${DEV_DISCORD_BOT_TOKEN}
      PROD_DISCORD_BOT_TOKEN: ${PROD_DISCORD_BOT_TOKEN}
      GUILD_ID: ${GUILD_ID}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    volumes:
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bot_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      GUILD_ID: ${GUILD_ID}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT_URL: ${DISCORD_REDIRECT_URL}
      DISCORD_TRACKED_ROLE_ID: ${DISCORD_TRACKED_ROLE_ID}
      BOT_API_URL: http://bot:8090
      JWT_SECRET: ${JWT_SECRET}
      MODERATOR_ROLE_IDS: ${MODERATOR_ROLE_IDS}
      ADMIN_ROLE_IDS: ${ADMIN_ROLE_IDS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bot_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - 5173:5173
    networks:
      - bot_network

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - bot_network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres
    networks:
      - bot_network

volumes:
  postgres_data:
networks:
  bot_network:
